import {GroupBox, LineEdit, Button, ComboBox, ListView} from "std-widgets.slint";

export global State {
  callback enter_key(string);
  callback listen(string, string);
}

component DataList inherits ListView {
    width: 150px;
    height: 150px;

}

export component MainWindow inherits Window {
  title: "Main Window";
  in-out property <string> key;
  in-out property <[string]> model: ["123"];
  width: 600px;
  height: 500px;
 
  VerticalLayout { 
    alignment:start;
    padding-left: 25px;
    padding-right: 25px;
 
    Text { 
      font-size: 27px;
      font-weight: 700;
      color: #6776FF;  
     }
 
    GroupBox{
       title:"API Key";
       LineEdit {
        edited(s) => {
          root.key = s;
        }
         placeholder-text: "请输入API KEY";
      }
    }
 
    Button {
       text: "start";
       clicked => {
        State.enter-key(root.key);
        }
    }

    box := ComboBox {
      model: root.model;
      current-value: "123";
    }

    Button {
          text: "listen";
          clicked => {
            State.listen(root.key, box.current-value);
         }
      }
  }
}
